import fs from "node:fs/promises";
import path from "node:path";

const KNOWLEDGE_BASE = "/Users/bono/.openclaw/workspace/juniper-knowledge";
const OUTPUT = path.join(process.cwd(), "lib", "knowledge-bundle.ts");

// Core files to include in full context (order matters)
const CORE_FILES = [
  "elearning/JUNIPER_ELEARNING_KNOWLEDGE.md",
  "ACCOMMODATION_OFFERS_AND_CONTRACTS.md",
  "BOOKING_FLOWS.md",
  "JUNIPER_API_KNOWLEDGE.md",
  "REQUEST_RESPONSE_SCHEMAS.md",
  "IMPLEMENTATION_EXAMPLES.md",
  "ERROR_WARNING_MATRIX.md",
  "ENDPOINT_TAXONOMY.md",
  "AUTH_MODEL.md",
  "OCTO_API.md",
  "elearning/FULL_EXTRACTION.md",
  "elearning/KEY_WORKFLOWS.md",
  "elearning/OPERATIONAL_RULES.md",
  "elearning/FAQs.md",
  "elearning/EDGE_CASES.md",
  "elearning/MODULE_SUMMARIES.md",
  "elearning/GLOSSARY.md",
];

async function bundle() {
  const parts: string[] = [];

  for (const relPath of CORE_FILES) {
    const fullPath = path.join(KNOWLEDGE_BASE, relPath);
    try {
      const content = await fs.readFile(fullPath, "utf8");
      parts.push(`--- SOURCE: ${relPath} ---\n${content.trim()}`);
    } catch {
      console.warn(`Skipping missing file: ${relPath}`);
    }
  }

  const bundled = parts.join("\n\n");
  const estimatedTokens = Math.ceil(bundled.split(/\s+/).length * 1.33);

  console.log(`Bundled ${parts.length} files, ~${estimatedTokens} tokens, ${bundled.length} chars`);

  const tsContent = `// Auto-generated by scripts/bundle-knowledge.ts — do not edit
// ${new Date().toISOString()} — ${parts.length} files, ~${estimatedTokens} tokens
export const KNOWLEDGE_BUNDLE = ${JSON.stringify(bundled)};
`;

  await fs.writeFile(OUTPUT, tsContent, "utf8");
  console.log(`Written to ${OUTPUT}`);
}

bundle().catch((err) => {
  console.error(err);
  process.exit(1);
});
